"""SIP plans (recurring mutual-fund investments with annual step-up)

Adds:
  * sip_plan table — a monthly SIP into one MF holding, with optional
    annual step-up % and an optional "paid from" cash account.
  * mf_txn.sip_plan_id — marks installments generated by a SIP plan.

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2026-07-22
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b2c3d4e5f6a7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'sip_plan',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('holding_id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.String(), nullable=False),
        sa.Column('day_of_month', sa.Integer(), nullable=True),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('step_up_pct', sa.String(), nullable=False),
        sa.Column('account_id', sa.Integer(), nullable=True),
        sa.Column('tags', sa.String(length=200), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=False),
        sa.Column('next_run_date', sa.Date(), nullable=True),
        sa.Column('note', sa.String(length=200), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['holding_id'], ['mf_holding.id']),
        sa.ForeignKeyConstraint(['account_id'], ['account.id']),
        sa.PrimaryKeyConstraint('id'),
    )

    with op.batch_alter_table('mf_txn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sip_plan_id', sa.Integer(), nullable=True))


def downgrade():
    with op.batch_alter_table('mf_txn', schema=None) as batch_op:
        batch_op.drop_column('sip_plan_id')

    op.drop_table('sip_plan')
