"""initial schema

Revision ID: d9eccfcbb934
Revises: 
Create Date: 2026-07-15 01:52:29.356087

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd9eccfcbb934'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('opening_balance', sa.String(), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('color', sa.String(length=24), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=True),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_is_read'), ['is_read'], unique=False)

    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('group', sa.String(length=40), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=4), nullable=False),
    sa.Column('bank', sa.String(length=100), nullable=True),
    sa.Column('principal', sa.String(), nullable=True),
    sa.Column('installment', sa.String(), nullable=True),
    sa.Column('interest_rate', sa.String(), nullable=False),
    sa.Column('compounding', sa.String(length=12), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('epf_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('member_id', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gold_holding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mf_holding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_code', sa.String(length=20), nullable=False),
    sa.Column('scheme_name', sa.String(length=160), nullable=False),
    sa.Column('fund_house', sa.String(length=120), nullable=True),
    sa.Column('plan_type', sa.String(length=10), nullable=True),
    sa.Column('asset_type', sa.String(length=10), nullable=True),
    sa.Column('goal', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mf_holding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mf_holding_scheme_code'), ['scheme_code'], unique=False)

    op.create_table('networth_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('cash_bank', sa.String(), nullable=True),
    sa.Column('funds', sa.String(), nullable=True),
    sa.Column('mf', sa.String(), nullable=True),
    sa.Column('gold', sa.String(), nullable=True),
    sa.Column('deposits', sa.String(), nullable=True),
    sa.Column('epf', sa.String(), nullable=True),
    sa.Column('stock', sa.String(), nullable=True),
    sa.Column('total', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('networth_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_networth_snapshot_date'), ['date'], unique=False)

    op.create_table('price_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=6), nullable=True),
    sa.Column('as_of', sa.Date(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=True),
    sa.Column('meta', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_cache_key'), ['key'], unique=True)

    op.create_table('setting',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('stock_holding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('budget_month', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('planned_amount', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_month', 'category_id', name='uq_budget_month_cat')
    )
    with op.batch_alter_table('budget_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_line_budget_month'), ['budget_month'], unique=False)

    op.create_table('epf_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('entry_type', sa.String(length=12), nullable=True),
    sa.Column('employee_share', sa.String(), nullable=True),
    sa.Column('employer_share', sa.String(), nullable=True),
    sa.Column('interest_amount', sa.String(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['epf_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gold_txn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=4), nullable=False),
    sa.Column('grams', sa.String(), nullable=False),
    sa.Column('price_per_gram', sa.String(), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['holding_id'], ['gold_holding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mf_txn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(length=6), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('units', sa.String(), nullable=False),
    sa.Column('nav', sa.String(), nullable=False),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['holding_id'], ['mf_holding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payee_memory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payee', sa.String(length=120), nullable=False),
    sa.Column('last_category_id', sa.Integer(), nullable=True),
    sa.Column('last_account_id', sa.Integer(), nullable=True),
    sa.Column('last_type', sa.String(length=10), nullable=True),
    sa.Column('uses', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['last_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['last_category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payee_memory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payee_memory_payee'), ['payee'], unique=True)

    op.create_table('recurring_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payee', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('transfer_account_id', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(length=10), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('month_of_year', sa.Integer(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('mode', sa.String(length=12), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['transfer_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_rule_next_due_date'), ['next_due_date'], unique=False)

    op.create_table('sinking_fund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('target_amount', sa.String(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_txn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('holding_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('qty', sa.String(), nullable=False),
    sa.Column('price_usd', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['holding_id'], ['stock_holding.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('transfer_account_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('payee', sa.String(length=120), nullable=True),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('budget_month', sa.Date(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['transaction.id'], ),
    sa.ForeignKeyConstraint(['transfer_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_budget_month'), ['budget_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transaction_date'))
        batch_op.drop_index(batch_op.f('ix_transaction_category_id'))
        batch_op.drop_index(batch_op.f('ix_transaction_budget_month'))
        batch_op.drop_index(batch_op.f('ix_transaction_account_id'))

    op.drop_table('transaction')
    op.drop_table('stock_txn')
    op.drop_table('sinking_fund')
    with op.batch_alter_table('recurring_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_rule_next_due_date'))

    op.drop_table('recurring_rule')
    with op.batch_alter_table('payee_memory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payee_memory_payee'))

    op.drop_table('payee_memory')
    op.drop_table('mf_txn')
    op.drop_table('gold_txn')
    op.drop_table('epf_entry')
    with op.batch_alter_table('budget_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_line_budget_month'))

    op.drop_table('budget_line')
    op.drop_table('stock_holding')
    op.drop_table('setting')
    with op.batch_alter_table('price_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_cache_key'))

    op.drop_table('price_cache')
    with op.batch_alter_table('networth_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_networth_snapshot_date'))

    op.drop_table('networth_snapshot')
    with op.batch_alter_table('mf_holding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mf_holding_scheme_code'))

    op.drop_table('mf_holding')
    op.drop_table('gold_holding')
    op.drop_table('epf_account')
    op.drop_table('deposit')
    op.drop_table('category')
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_is_read'))
        batch_op.drop_index(batch_op.f('ix_alert_dedupe_key'))

    op.drop_table('alert')
    op.drop_table('account')
    # ### end Alembic commands ###
